#!/usr/bin/env bash

sudo port selfupdate
sudo port upgrade outdated

# version Control
sudo port install git

# install required and other useful binaries
sudo port install postgresql93-server
sudo port install geos proj postgis2 libgeoip
sudo port install gdal +geos

# PIL / Pillow dependencies
sudo port install lcms2 jpeg libpng webp

# XML parsing tools
sudo port install libxml2 libxslt

# image optimization utils
sudo port install pngcrush
sudo port install advancecomp
sudo port install jpegoptim
sudo port install optipng

sudo port install nodejs
