#!/usr/bin/env bash

sudo port selfupdate
sudo port upgrade outdated

# version Control
sudo port install git

# install required and other useful binaries
sudo port install postgresql93-server
sudo port install geos proj
sudo port install postgis2
sudo port install gdal +geos
sudo port install libgeoip

# PIL / Pillow dependencies
sudo port install lcms2
sudo port install jpeg
sudo port install libpng
sudo port install webp

# XML parsing tools
sudo port install libxml2
sudo port install libxslt

# image optimization utils
sudo port install pngcrush
sudo port install advancecomp
sudo port install jpegoptim
sudo port install gifsicle
sudo port install optipng

sudo port install nodejs
